# Generated by Django 4.1.9 on 2023-05-11 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Edition",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=50, verbose_name="Name")),
                ("year", models.CharField(max_length=50, verbose_name="Year")),
                ("pages", models.CharField(max_length=50, verbose_name="Pages")),
                ("pub_num", models.CharField(max_length=50, verbose_name="Pub Number")),
            ],
            options={
                "verbose_name": "Edition",
                "verbose_name_plural": "Editions",
            },
        ),
        migrations.CreateModel(
            name="Magazine",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=50, verbose_name="Name")),
            ],
            options={
                "verbose_name": "Magazine",
                "verbose_name_plural": "Magazines",
            },
        ),
        migrations.AddField(
            model_name="edition",
            name="magazine",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="app.magazine"
            ),
        ),
    ]
