"""Initial migration for the example app."""

# Generated by Django 5.1.3 on 2024-12-15 03:54

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    """Initial migration."""
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EmbargoRegion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "market_tier",
                    models.IntegerField(choices=[(1, "Tier 1"), (2, "Tier 2"), (3, "Tier 3")]),
                ),
                (
                    "content_restrictions",
                    models.TextField(help_text="Special content restrictions for this region"),
                ),
                (
                    "typical_embargo_days",
                    models.IntegerField(
                        help_text="Typical embargo period in days for this region",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="PublicationTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("usage_count", models.IntegerField(default=0)),
                ("is_approved", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("bio", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Author",
                "verbose_name_plural": "Authors",
                "ordering": ["name"],
                "indexes": [models.Index(fields=["name"], name="example_aut_name_aaf9d6_idx")],
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="example.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Magazine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Name")),
                (
                    "accepts_new_articles",
                    models.CharField(
                        choices=[("yes", "Yes"), ("no", "No"), ("maybe", "Maybe")],
                        default="yes",
                        max_length=10,
                        verbose_name="Accepts New Articles",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Magazine",
                "verbose_name_plural": "Magazines",
                "ordering": ["name"],
                "indexes": [models.Index(fields=["name"], name="example_mag_name_23d5fe_idx")],
            },
        ),
        migrations.CreateModel(
            name="Edition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Name")),
                ("year", models.CharField(max_length=50, verbose_name="Year")),
                ("pages", models.CharField(max_length=50, verbose_name="Pages")),
                (
                    "pub_num",
                    models.CharField(max_length=50, verbose_name="Publication Number"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "magazine",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="example.magazine",
                    ),
                ),
            ],
            options={
                "verbose_name": "Edition",
                "verbose_name_plural": "Editions",
                "ordering": ["magazine", "name"],
            },
        ),
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("word_count", models.PositiveSmallIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("archived", "Archived"),
                            ("published", "Published"),
                            ("pending", "Pending"),
                            ("locked", "Locked"),
                            ("on_hold", "On Hold"),
                            ("on_review", "On Review"),
                            ("modified", "Modified"),
                            ("moderated", "Moderated"),
                            ("new", "New"),
                            ("needs_review", "Needs Review"),
                            ("blocked", "Blocked"),
                            ("banned", "Banned"),
                            ("verified", "Verified"),
                            ("confirmed", "Confirmed"),
                            ("canceled", "Canceled"),
                            ("approved", "Approved"),
                            ("accepted", "Accepted"),
                            ("submitted", "Submitted"),
                            ("saved", "Saved"),
                            ("deleted", "Deleted"),
                            ("denied", "Denied"),
                            ("flagged", "Flagged"),
                            ("granted", "Granted"),
                            ("good", "Good"),
                            ("hidden", "Hidden"),
                            ("highlighted", "Highlighted"),
                            ("hold", "Hold"),
                            ("junk", "Junk"),
                            ("kicked", "Kicked"),
                            ("killed", "Killed"),
                            ("inactive", "Inactive"),
                            ("in_progress", "In Progress"),
                            ("unpublished", "Unpublished"),
                            ("unverified", "Unverified"),
                            ("yes", "Yes"),
                            ("yet_to_be_published", "Yet to be Published"),
                            ("to_be_reviewed", "To Be Reviewed"),
                            ("trashed", "Trashed"),
                            ("troubled", "Troubled"),
                            ("rejected", "Rejected"),
                            ("removed", "Removed"),
                            ("edited", "Edited"),
                            ("error", "Error"),
                            ("waiting", "Waiting"),
                            ("working", "Working"),
                            ("queued", "Queued"),
                            ("questionable", "Questionable"),
                            ("unconfirmed", "Unconfirmed"),
                            ("reverted", "Reverted"),
                            ("reviewed", "Reviewed"),
                            ("expired", "Expired"),
                            ("wip", "WIP"),
                            ("beta", "Beta"),
                        ],
                        default="draft",
                        max_length=30,
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(
                        choices=[
                            (1, "Low"),
                            (2, "Medium"),
                            (3, "High"),
                            (4, "Critical"),
                            (5, "Urgent"),
                            (6, "Immediate"),
                            (7, "None"),
                            (8, "Immense"),
                            (9, "Extreme"),
                            (10, "Maximum"),
                            (11, "Total"),
                            (12, "Absolute"),
                            (13, "Alpha"),
                            (14, "Gamma"),
                            (15, "Master"),
                            (16, "Major"),
                            (17, "Minor"),
                            (18, "Normal"),
                            (19, "Crucial"),
                            (20, "Nada"),
                            (21, "Miniscule"),
                            (22, "Micro"),
                            (23, "Excessive"),
                            (24, "Overwhelming"),
                            (25, "Immensely High"),
                            (26, "Overly High"),
                            (27, "Enormous"),
                            (28, "Gigantic"),
                            (29, "Tomorrow"),
                            (30, "Later"),
                            (31, "Can't Be Bothered"),
                            (32, "Not Important"),
                            (33, "Who Cares"),
                            (34, "Non-Eucledian"),
                        ],
                        default=18,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                ("authors", models.ManyToManyField(to="example.author")),
                ("categories", models.ManyToManyField(to="example.category")),
                (
                    "edition",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="example.edition",
                    ),
                ),
                (
                    "magazine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="example.magazine",
                    ),
                ),
            ],
            options={
                "verbose_name": "Article",
                "verbose_name_plural": "Articles",
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="PublishingMarket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the market. Either a region, country, or city/market.",
                        max_length=100,
                    ),
                ),
                (
                    "market_size",
                    models.IntegerField(
                        default=0,
                        help_text="Market size in millions of potential readers",
                    ),
                ),
                (
                    "active_publications",
                    models.IntegerField(
                        default=0,
                        help_text="Number of active publications in this market",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="example.publishingmarket",
                    ),
                ),
            ],
            options={
                "verbose_name": "Publishing Market",
                "verbose_name_plural": "Publishing Markets",
                "ordering": ["name"],
            },
        ),
        migrations.AddIndex(
            model_name="category",
            index=models.Index(fields=["name"], name="example_cat_name_135419_idx"),
        ),
        migrations.AddIndex(
            model_name="edition",
            index=models.Index(fields=["name"], name="example_edi_name_434bee_idx"),
        ),
        migrations.AddIndex(
            model_name="edition",
            index=models.Index(fields=["year"], name="example_edi_year_f885a5_idx"),
        ),
        migrations.AddIndex(
            model_name="article",
            index=models.Index(fields=["title"], name="example_art_title_c6a4a6_idx"),
        ),
    ]
