# Generated by Django 5.2.1 on 2025-05-23 16:22

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("example", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ModelWithPKIDAndUUIDId",
            fields=[
                ("pkid", models.AutoField(primary_key=True, serialize=False)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("name", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "Model with UUID ID",
                "verbose_name_plural": "Models with UUID ID",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ModelWithUUIDPk",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "Model with UUID PK",
                "verbose_name_plural": "Models with UUID PK",
                "ordering": ["name"],
                "constraints": [models.UniqueConstraint(fields=("name",), name="unique_name_constraint")],
            },
        ),
    ]
