# Generated by Django 5.2.1 on 2026-05-14 23:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('example', '0002_modelwithpkidanduuidid_modelwithuuidpk'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spotlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('object_id', models.PositiveIntegerField()),
                ('featured_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Spotlight',
                'verbose_name_plural': 'Spotlights',
                'ordering': ['-featured_at'],
            },
        ),
    ]
