# Generated by Django 5.2.1 on 2026-06-13 06:04

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0003_spotlight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelwithpkidanduuidid',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
